# Generated by Django 5.1 on 2024-08-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelApp', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='plus',
            old_name='name',
            new_name='fullname',
        ),
    ]
